// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	OutputAchievementTags string
	OutputAchievements    string
	Tags                  string
	TodoDetails           string
	Todos                 string
	Users                 string
}{
	OutputAchievementTags: "output_achievement_tags",
	OutputAchievements:    "output_achievements",
	Tags:                  "tags",
	TodoDetails:           "todo_details",
	Todos:                 "todos",
	Users:                 "users",
}
